### ISSUE TITLE
economicEvents filtering

### ISSUE THREAD

**Issue by vcuculo** [dyne/reflow-os#23]
Following the resolution of issue #16 , it would be useful to replicate the filtering feature also for `economicEvents`.
Query is already present, but seems to ignore the parameters. in particular `action`, `startDate`, `endDate` and `receiverId`.

```gql
query{
  economicEventsFiltered(action:"transfer", receiverId:"01FKQVX0JNWE9QNX437SKTPSTM", startDate:"2022-01-01T13:21:31.335000Z", endDate:"2022-01-10T14:21:31.335000Z"){
    id
  }
}
```

**Comment by srfsh** [comment]
> Following the resolution of issue #16 , it would be useful to replicate the filtering feature also for `economicEvents`. Query is already present, but seems to ignore the parameters. in particular `action`, `startDate`, `endDate` and `receiverId`.
> 
> ```graphql
> query{
>   economicEventsFiltered(action:"transfer", receiverId:"01FKQVX0JNWE9QNX437SKTPSTM", startDate:"2022-01-01T13:21:31.335000Z", endDate:"2022-01-10T14:21:31.335000Z"){
>     id
>   }
> }
> ```

Hi, Vittorio.

Thanks for reporting.  I'll work on it and report you back!  ^^

Cheers,
srfsh

**Comment by srfsh** [comment]
I've fixed this in the latest image I released.  Can you test the changes?  It is also live on http://reflow-demo.dyne.org:4000.

**Comment by vcuculo** [comment]
Perfect, thank you!
