### ISSUE TITLE
Wish: graphql mutation for creating (and approving) users

### ISSUE THREAD

**Issue by ocataco** [dyne/reflow-os#4]
For the simulations I'm working on it would be great to script the making and approving of test users (with agents) instead of doing this by hand.

**Comment by mayel** [comment]
Hi @ocataco that's easy enough do to in Elixir, see for example the seeds script: https://github.com/dyne/bonfire-app/blob/main/flavours/reflow/repo/seeds.exs#L14

**Comment by mayel** [comment]
As you probably found, there isn't currently a graphql API for users (other than simply logging in), though that's of course somewhere on the to do list...

**Comment by srfsh** [comment]
Hi @ocataco,

Can you fetch the latest source and try this make command to create verified users (everything must be set up and this must be run while the application is not running):

```
make tasks.create_user email="bob@example.com" pass="bobthehunter2"
```

You can also pass the arguments `user` to specify the username, `name` to specify the full name of the user.  If not given, those fields will be randomly generated.

An example with all the arguments:
```
make tasks.create_user email="bob@example.com" pass="bobthehunter2" user="bobby" name="Bob Smith"
```
