### ISSUE TITLE
createOffer requires `action_id`

### ISSUE THREAD

**Issue by vcuculo** [dyne/reflow-os#7]
The following mutation

```
mutation {
 createOffer(intent: {
      action: "transfer",
      name: "Donazione",
      receiver:"01F3MHQ0KWJC7M19B1E8BXVY46",
      resourceConformsTo: "01FE4094Y6J99MEDWXBXQCAJF8",
      availableQuantity: {hasUnit: "01FFJEBJ4S4E4ZDWZNEWYFZYD7", hasNumericalValue: 10}
      due: "2021-09-20T14:10:20+01:00"
}) {
  intent {
    id
    name
  }
}
}
```

results in 

 ```
{
   "data": {
     "createOffer": null
   },
   "errors": [
     {
       "code": "required",
       "field": "action_id",
       "locations": [
         {
           "column": 2,
           "line": 3
         }
       ],
       "message": "can't be blank",
       "path": [
         "createOffer"
       ],
       "status": 200
     }
   ]
 }
```

but `action_id` field is not defined AFAIK

**Comment by adam-burns** [comment]
Can you confirm the host/IP address of the backend GraphQL you are using to attempt this interaction?

**Comment by vcuculo** [comment]
It is deployed on localhost.

**Comment by adam-burns** [comment]
OK. Thanks. The reason I asked was just to confirm that you were interacting with this repo's Bonfire backend, and not the CommonsPub (ZenPub flavour) backend.

**Comment by vcuculo** [comment]
Yes, I can confirm that I'm currently testing locally the Bonfire backend.

**Comment by srfsh** [comment]
Hi @vcuculo,

I pushed a fix to the ValueFlows code.  Can you try again and report me back?

Thanks,
srfsh

**Comment by mayel** [comment]
Merged upstream, thanks all!

**Comment by vcuculo** [comment]
> Hi @vcuculo,
> 
> I pushed a fix to the ValueFlows code. Can you try again and report me back?
> 
> Thanks, srfsh

Thank you all, I can confirm this is fixed.
